import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useForm, SubmitHandler } from 'react-hook-form';

const MAX_STEP_COUNT = 4;

const Home: NextPage = () => {
  const [step, setStep] = React.useState(1);
  const completeStep = () => {
    setStep(currentStep => currentStep + 1);
  }

  const goBack = () => {
    setStep(currentStep => currentStep - 1);
  }
  const renderButton = () => {
    if (step > 3) {
      return undefined
    } else if (step === 3){
      return (
        <button
              type="submit"
              className={isValid ? 'btn-primary' : 'btn-inactive'}
              disabled={!isValid}
            >
              Create Account
            </button>
      )
    } else {
      return (
        <button
              type="button"
              className={isValid ? 'btn-primary' : 'btn-inactive'}
              onClick={completeStep}
              disabled={!isValid}
            >
              Next Step
            </button>
      )
    }
  }
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors, isValid },
  } = useForm({mode: "all"}); // validate on every keypress

  const onSubmit: SubmitHandler<any> = (data: any) => {
    // console.log('Submitted data', data);
    alert(JSON.stringify(data));
    completeStep();
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>A MultiStep Form Using react hooks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div>
          <h2>Multi Step Form Using React Hooks</h2>
          <div><p><progress max={MAX_STEP_COUNT} value={step}> </progress></p></div>
          
          <form onSubmit={handleSubmit(onSubmit)}>

          {step === 1 &&<div className={styles.inputGroup}>
            <input
              {...register('name', {
                required: true,
                maxLength: 65,
                minLength: 4,
                pattern: /[A-Za-z0-9_.-]/,
              })}
              type="text"
              placeholder="Enter Your Name "
              className={styles.formInput}
            />
            <p className={styles.formError}>
              {errors.name && <span> Name is required</span>}
            </p>
         </div>}

         {step === 2 &&<div className={styles.inputGroup}>
            <input
              {...register('phone', {
                required: true,
                maxLength: 15,
                minLength: 6,
              })}
              type="number"
              placeholder="Enter Your Phone Number "
              className={styles.formInput}
            />
            <p className={styles.formError}>
              {errors.phone && <span> Phone is required</span>}
            </p>
         </div>}
        
         {step === 3 && <div className={styles.inputGroup}>
          <input
              {...register('email', {
                required: true,
                maxLength: 65,
                minLength: 4,
              })}
              type="email"
              placeholder="Enter your email address "
              className={styles.formInput}
            />
            <p className={styles.formError}>
              {errors.email && <span> Email is required</span>}
            </p>{' '}
          </div>}       

          {step > 1  && <span><button
                  type="button"
                  className={step === 4 ? 'hidden' :'btn-secondary'}
                  onClick={goBack}
                  >
                    Back
              </button>
            </span>}
            {renderButton()}
            {step === 4 && <div>Congratulations</div>}

          </form>
          <div>
            <pre>
              {JSON.stringify(watch(), null, 2)}
            </pre>
          </div>
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://ericmabo.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by EricMabo.com
        </a>
      </footer>
    </div>
  )
}

export default Home
